In [2]:
import numpy as np
import roboticstoolbox as rtb
from spatialmath import *
from math import pi
import matplotlib.pyplot as plt
from matplotlib import cm
np.set_printoptions(linewidth=100, formatter={'float': lambda x: f"{x:8.4g}" if abs(x) > 1e-10 else f"{0:8.4g}"})

%matplotlib notebook

The Toolbox supports models defined using a number of different conventions.  We will load a very classical model, a Puma560 robot defined in terms of standard Denavit-Hartenberg parameters

In [3]:
p560 = rtb.models.Z1()

Now we can display the simple Denavit-Hartenberg parameter model

In [4]:
print(p560)

ERobot: Z1_DESCRIPTION (by Unitree), 6 joints (RRRRRR), 1 gripper, dynamics, geometry, collision
┌─────┬────────────────┬───────┬────────┬───────────────────────────────┐
│link │      link      │ joint │ parent │      ETS: parent to link      │
├─────┼────────────────┼───────┼────────┼───────────────────────────────┤
│   0 │ world          │       │ BASE   │                               │
│   1 │ link00         │       │ world  │ SE3()                         │
│   2 │ link01         │     0 │ link00 │ SE3(0, 0, 0.0585) ⊕ Rz(q0)    │
│   3 │ link02         │     1 │ link01 │ SE3(0, 0, 0.045) ⊕ Ry(q1)     │
│   4 │ link03         │     2 │ link02 │ SE3(-0.35, 0, 0) ⊕ Ry(q2)     │
│   5 │ link04         │     3 │ link03 │ SE3(0.218, 0, 0.057) ⊕ Ry(q3) │
│   6 │ link05         │     4 │ link04 │ SE3(0.07, 0, 0) ⊕ Rz(q4)      │
│   7 │ link06         │     5 │ link05 │ SE3(0.0492, 0, 0) ⊕ Rx(q5)    │
│   8 │ @gripperStator │       │ link06 │ SE3(0.051, 0, 0)              │
└─────┴────────

The first table shows the kinematic parameters, and from the column titles we can see clearly that this is expressed in terms of standard Denavit-Hartenberg parameters.  The first column shows that the joint variables qi are rotations since they are in the θ column.  Joint limits are also shown.  Joint flip (motion in the opposite sense) would be indicated by the joint variable being shown as for example like `-q3`, and joint offsets by being shown as for example like `q2 + 45°`.

The second table shows some named joint configurations.  For example `p560.qr` is 

In [5]:
p560.qr

array([0.000922,  0.00068, -0.003654, -0.07501, -0.00013,  3.5e-05])

If the robot had a base or tool transform they would be listed in this table also.

This object is a subclass of `DHRobot`, equivalent to the `SerialLink` class in the MATLAB version of the Toolbox.
This class has many methods and attributes, and we will explore some of them in this notebook.

We can easily display the robot graphically

In [7]:
p560.plot(p560.qn);

where `qn` is one of the named configurations shown above, and has the robot positioned to work above a table top.  You can use the mouse to rotate the plot and view the robot from different directions.  The grey line is the _shadow_ which is a projection of the robot onto the xy-plane.

In this particular case the end-effector pose is given by the forward kinematics

In [8]:
p560.fkine(p560.qn)

   0.997    -0.0007951 -0.07698   0.08636   
   0.0007893  1        -0.0001061  6.023e-05  
   0.07698   4.502e-05  0.997     0.1785    
   0         0         0         1         


which is a 4x4 SE(3) matrix displayed in a color coded way with rotation matrix in red, translation vector in blue, and constant elements in grey.  This is an instance of an `SE3` object safely encapsulates the SE(3) matrix.  This class, and related ones, are implemented by the [Spatial Math Toolbox for Python](https://github.com/petercorke/spatialmath-python).

You can verify the end-effector position, the blue numbers are from top to bottom the x-, y- and z-coordinates of the end-effector position, match the plot shown above.

We can manually adjust the joint angles of this robot (click and drag the sliders) to see how the shape of the robot changes and how the end-effector pose changes

In [9]:
#p560.teach(); # works from console, hangs in Jupyter

AttributeError: 'Swift' object has no attribute '_add_teach_panel'

An important problem in robotics is _inverse kinematics_, determining the joint angles to put the robot's end effector at a particular pose.

Suppose we want the end-effector to be at position (0.5, 0.2, 0.1) and to have its gripper pointing (its _approach vector_) in the x-direction, and its fingers one above the other so that its _orientation vector_ is parallel to the z-axis.

We can specify that pose by composing two SE(3) matrices:

1. a pure translation
2. a pure rotation defined in terms of the orientation and approach vectors

In [10]:
T = SE3(0.5, 0.2, 0.5) * SE3.OA([0,0,1], [1,0,0])
T

   0         0         1         0.5       
   1         0         0         0.2       
   0         1         0         0.5       
   0         0         0         1         


Now we can compute the joint angles that results in this pose

In [12]:
sol = p560.ikine_LM(T)

which returns the joint coordinates as well as solution status

In [13]:
sol

IKSolution(q=array([  0.1064,    2.402,   -2.941,   0.5383,    1.356,    1.571,  -0.8864]), success=True, iterations=1297, searches=44, residual=1.147452607923145e-07, reason='Success')

indicating, in this case, that there is no failure. The joint coordinates are

In [14]:
sol.q

array([  0.1064,    2.402,   -2.941,   0.5383,    1.356,    1.571,  -0.8864])

and we can confirm that this is indeed an inverse kinematic solution by computing the forward kinematics

In [15]:
p560.fkine(sol.q)

   0.002073 -2.496e-07  1         0.5       
   1        -3.64e-06 -0.002073  0.2       
   3.64e-06  1         2.421e-07  0.5       
   0         0         0         1         


which matches the original transform.

A simple trajectory between two joint configuration is

In [19]:
q2=sol.q[:6] #ignore gripper

In [22]:
qt = rtb.tools.trajectory.jtraj(p560.qz, q2, 250)

The result is a _namedtuple_ with attributes `q` containing the joint angles, as well as `qd`, `qdd` and `t` which hold the joint velocity, joint accelerations and time respectively.  

The joint angles are a matrix with one column per joint and one row per timestep, and time increasing with row number.

In [40]:
qt.q
id=np.arange(250)
zeros=np.zeros(250)
np.hstack((id[:,None],qt.q,zeros[:,None],qt.qd,zeros[:,None])) #save this to traj file for Z1


array([[       0, 0.000922,  0.00068, ...,        0,        0,        0],
       [       1, 0.0009221, 0.0006815, ..., 0.0006509, 0.0007539,        0],
       [       2, 0.0009225, 0.0006923, ..., 0.002583, 0.002992,        0],
       ...,
       [     247,   0.1064,    2.402, ..., 0.002583, 0.002992,        0],
       [     248,   0.1064,    2.402, ..., 0.0006509, 0.0007539,        0],
       [     249,   0.1064,    2.402, ...,        0,        0,        0]])

We can plot this trajectory as a function of time using the convenience function `qplot`

In [26]:
rtb.tools.trajectory.xplot(qt.q, block=False)

AttributeError: module 'roboticstoolbox.tools.trajectory' has no attribute 'xplot'

and then we can animate this

In [29]:
p560.plot(qt.q, dt=0.04);

_Note: animation not working in Jupyter..._

The inverse kinematic solution was found using an iterative numerical procedure.  It is quite general but it has several drawbacks:
- it can be slow
- it may not find a solution, if the initial choice of joint coordinates is far from the solution (in the case above the default initial choice of all zeros was used)
- it may not find the solution you want, in general there are multiple solutions for inverse kinematics.  For the same end-effector pose, the robot might:
    - have it's arm on the left or right of its waist axis, 
    - the elbow could be up or down, and
    - the wrist can flipped or not flipped.  For a two-finger gripper a rotation of 
      180° about the gripper axis leaves the fingers in the same configuration.

Most industrial robots have a _spherical wrist_ which means that the last three joint axes intersect at a single point in the middle of the wrist mechanism.  We can test for this condition

In [30]:
p560.isspherical()

AttributeError: 'Z1' object has no attribute 'isspherical'

This greatly simplifies things because the last three joints only control orientation and have no effect on the end-effector position.  This means that only the first three joints define position $(x_e, y_e, z_e)$.  Three joints that control three unknowns is relatively easy to solve for, and analytical solutions (complex trigonmetric equations) can be found, and in fact have been published for most industrial robot manipulators.

The Puma560 has an analytical solution.  We can request the solution with the arm to the left and the elbow up, and the wrist not flipped by using the configuration string `"lun"`


In [31]:
sol = p560.ikine_a(T, "lun")
sol

AttributeError: 'Z1' object has no attribute 'ikine_a'

which is different to the values found earlier, but we can verify it is a valid solution

In [21]:
p560.fkine(sol.q)

   0         0         1         0.5       
   1         0         0         0.2       
   0         1         0         0.5       
   0         0         0         1         


In fact the solution we found earlier, but didn't explicitly specify, is the right-handed elbow-up configuration

In [22]:
sol = p560.ikine_a(T, "run")
sol.q

array([  0.6629,   0.5682,    2.983,   -2.436,   -1.252,   -1.832])

Other useful functions include the manipulator Jacobian which maps joint velocity to end-effector velocity expressed in the world frame

In [23]:
p560.jacob0(p560.qn)

array([[  0.1501,  0.01435,   0.3197,        0,        0,        0],
       [  0.5963,        0,        0,        0,        0,        0],
       [       0,   0.5963,    0.291,        0,        0,        0],
       [       0,        0,        0,   0.7071,        0,        1],
       [       0,       -1,       -1,        0,       -1,        0],
       [       1,        0,        0,  -0.7071,        0,        0]])